--- !ditz.rubyforge.org,2008-03-06/project 
name: mitchscripts
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: mitchscripts
- !ditz.rubyforge.org,2008-03-06/component 
  name: sansa
releases: []

