#!/usr/bin/env perl
use strict;
use warnings;

our $have_number_bytes_human;

BEGIN {
    eval { require Number::Bytes::Human; };
    $have_number_bytes_human = not $@;
}

#### number formatters

sub dont_format {
    return shift;
}

sub humanize_numbers {
    my $value = shift;
    if ($value =~ /^[0-9]+$/) {
	return Number::Bytes::Human::format_bytes($value);
    }
    return $value;
}

#### writers

sub csv_writer {
    my ($lines, $columns) = @_;
    
    printf "%s\n", join(',', map { uc $_ } @{$columns});
    foreach my $line (@{$lines}) {
	printf "%s\n", join(',', @{$line});
    }
}

sub plain_writer {
    my ($lines, $columns) = @_;

    my $formatstring = join(' ', ('%-8s') x scalar( @{$columns} )) . "\n";

    foreach my $line (@{$lines}) {
	printf $formatstring, @{$line};
    }
    
}

#### parse commandline parameters

my $flag = shift @ARGV // '';

if ($flag eq '-h') {
    print <<"END";
$0 - print zfs compression statistics
usage:
  -h    - show this help
  -H    - use human-readable output:
           - numbers with suffixes like G, M, k
             (needs Number::Bytes::Human)
           - reorder columns
           - plain text instead of CSV
END
    exit;
}

my $formatter = \&dont_format;
my @columns = qw( name used logicalused localused compression compressratio );
my $writer = \&csv_writer;
if ($flag eq '-H') {
    if ($have_number_bytes_human) {
	$formatter = \&humanize_numbers;
    }
    else {
	warn "Number::Bytes::Human not found, using plain numbers\n";
    }
    @columns = qw( compression compressratio localused name );
    $writer = \&plain_writer;
}

#### gather data

my @pools;
open my $zpool, "zpool list -H -o name|" or die "can't open zpool: $!";
while (my $line = <$zpool>) {
    chomp $line;
    push @pools, $line;
}
close $zpool or die "can't close zpool: $!";

my $data;
foreach  my $pool (@pools) {
    open my $zfs, "zfs get -H -o name,property,value compression,compressratio,used,logicalused,mountpoint,canmount -p -r -t filesystem $pool|" or die "can't open zfs for pool $pool: $!";
    while (my $line = <$zfs>) {
	chomp $line;
	my ($name, $property, $value) = split /\t/, $line, 3;
	$data->{$name}->{$property} = $value;

	if ($property eq 'mountpoint') {
	    my $mountpoint = $value;
	    my $localused = '';
	    if ( -d $mountpoint ) {
		open my $df, "df --output=used --block-size 1 $mountpoint|" or die "can't open df for $mountpoint: $!";
		<$df>; # skip first line
		$localused = <$df>;
		$localused =~ tr/0-9//cd;
		close $df or die "can't open df for $mountpoint: $!";
	    }
	    $data->{$name}->{'localused'} = $localused;
	    $data->{$name}->{'name'} = $name;
	}
    }
    close $zfs or die "can't close zfs pool $pool: $!";
}

#### format data

my @rows;
foreach my $mountpoint (sort keys %{$data}) {
    my $filesystem = $data->{$mountpoint};
    next if ($filesystem->{'canmount'} // '') eq 'off';
    
    my @cols = ();
    foreach my $property (@columns) {
	my $unformatted_value = $filesystem->{$property} // '';
	my $formatted_value = &{$formatter}($unformatted_value);
	push @cols, $formatted_value;
    }
    push @rows, [ @cols ];
}

#### print results

&{$writer}(\@rows, \@columns);
