#!/bin/bash


echo "               db"
echo "              dPYb"
echo "             dP  Yb"
echo "            dP    Yb"
echo "           dP  db  Yb       Please remember"
echo "          dP   88   Yb      that your .aliases"
echo "         dP    88    Yb     have moved and update"
echo "        dP     YP     Yb    this account!"
echo "       dP              Yb"
echo "      dP       db       Yb"
echo "     dP        YP        Yb"
echo "    dP                    Yb"
echo "   d888888888888888888888888b"
echo

sleep 5
