#!/bin/bash
#
# wait until syncthing is idle
#
# needs dzen2

show_in_dzen2()
{
    dzen2 -bg darkred -fg grey80 -fn fixed -l 2 -e "button1=exec:touch $KILLTRIGGER;onstart=uncollapse;enterslave=collapse;entertitle=uncollapse" -ta left "$@"
}

warn_and_exit()
{
    echo "$@" >&2
    ( echo "$@" | show_in_dzen2 -p 2 ) &
    exit 1
}

is_still_syncing()
{
    STATUS=$(~/git/mitchscripts/bash/syncthing_status)
    case $STATUS in
	'')
	    return 1
	    ;;

	'[ST:gone]')
	    warn_and_exit "Syncthing isn't running!"
	    ;;
	
	'[ST:offl]')
	    warn_and_exit "Syncthing is offline"
	    ;;

	*)
	    return 0
	    ;;
    esac
}

TIMER=2

KILLTRIGGER=/tmp/stop-wait-for-dropbox-flag

# wait until idle
if is_still_syncing; then

    if [ "$DISPLAY" ] && command -v dzen2 >/dev/null ; then

        # graphical

	rm -f $KILLTRIGGER
	(
	    echo '^tw()Waiting for Syncthing to settle...'
	    while [ ! -e $KILLTRIGGER ] && is_still_syncing; do
		echo "$STATUS" | tr ^ \'
		sleep $TIMER
	    done
	) | show_in_dzen2

	rm -f $KILLTRIGGER

    else

        # text only

	echo -n 'Waiting for Syncthing to settle...'
	while is_still_syncing; do
	    sleep $TIMER
	    echo -n .
	done
	echo
	echo

    fi

fi
