#!/bin/bash
#
# wait until syncthing is idle
#
# optionally needs dzen2 and zenity

# is there a syncthing?
if ! pidof syncthing >/dev/null ; then
    # warn
    echo "Syncthing isn't running!" >&2
    zenity --warning --text="Syncthing isn't running!" 2>/dev/null ||  true
    # we're finished, nothing to do :)
    exit 1
fi

is_still_running()
{
    STATUS=$(~/git/mitchscripts/bash/syncthing_status)
    [ "$STATUS" ]
}

TIMER=2

KILLTRIGGER=/tmp/stop-wait-for-dropbox-flag

# wait until idle
if is_still_running; then

    if [ "$DISPLAY" ] && command -v dzen2 >/dev/null ; then

        # graphical

	rm -f $KILLTRIGGER
	(
	    echo '^tw()Waiting for Syncthing to settle...'
	    while [ ! -e $KILLTRIGGER ] && is_still_running; do
		echo "$STATUS" | tr ^ \'
		sleep $TIMER
	    done
	) | dzen2 -bg darkred -fg grey80 -fn fixed -l 2 -e "button1=exec:touch $KILLTRIGGER;onstart=uncollapse;enterslave=collapse;entertitle=uncollapse" -ta left

	rm -f $KILLTRIGGER

    else

        # text only

	echo -n 'Waiting for Syncthing to settle...'
	while is_still_running; do
	    sleep $TIMER
	    echo -n .
	done
	echo
	echo

    fi

fi
